# This is the Plex CFN - May run more templates from here - but most likely leverage Ansible from here on out
AWSTemplateFormatVersion: "2010-09-09"
Description: Mail CloudFormation templates
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: VPC & Network Configuration
      Parameters: [VPCID]
    ParameterLabels:
      VPCID:
        default: VPC ID
Parameters:
  VPCID:
    Type: List<AWS::EC2::VPC::Id>
  KeyPair:
    Description: Select an SSH Key for the instances. For security reaons you may want to upload your own and select that.
    Type: AWS::EC2::KeyPair::KeyName
  S3TemplateBucket:
    Type: String
    Description: The name of the S3 Bucket that contains all our template resources
  S3TemplateKey:
    Description: The url for this git package
    Type: String
    Default: "https://github.com/lordmuffin/aws-cfn-plex.git"
  S3TemplateBucketUrl:
    Description: The url for aws buckets
    Type: String
    Default: "https://s3.amazon.com"
Resources:
  MailLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket:
        S3Key:
    Description: Some Lambda Function
    MemorySize: 128
    Handler: lambda_handler
    Role:
    Timeout: 5
    Runtime: python2.7
  MailInboxSNSTopic:
    DependsOn: Lambda
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        -
          Endpoint:
            Fn::GetAtt:
              - "MailInboxSNS"
              - "Arn"
          Protocol: "sns"
      TopicName: "MailInboxSNS"
  MailBounceSNSTopic:
    DependsOn: Lambda
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        -
          Endpoint:
            Fn::GetAtt:
              - "MailBounceSNS"
              - "Arn"
          Protocol: "sns"
      TopicName: "MailBounceSNS"

  LambdaSNSTopic:
    DependsOn: Lambda
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        -
          Endpoint:
            Fn::GetAtt:
              - "Lambda"
              - "Arn"
          Protocol: "lambda"
      TopicName: "Lambda"
